server:
  port: 9090

spring:
  datasource:
    url: jdbc:sqlite:data/tradebot.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  sql:
    init:
      mode: always

tradebot:
  api:
    finnhub-key: ${FINNHUB_API_KEY:}
    coingecko-key: ${COINGECKO_API_KEY:}
    twelvedata-key: ${TWELVEDATA_API_KEY:}
  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN:}
    group-chat-id: ${TELEGRAM_BOT_GROUP_CHAT_ID:}
