# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean verify
      
    - name: Generate code coverage badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: target/site/jacoco/jacoco.csv
        coverage-badge-filename: badge-coverage.svg
        coverage-label: Coverage
        generate-coverage-badge: true
        generate-summary: true
        generate-workflow-summary: true
        workflow-summary-heading: "Code Coverage"
        
    - name: Commit coverage badge
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${GIT_AUTH_TOKEN}@github.com/${{ github.repository }}
        git add .github/badges/*
        git commit -m "Update code coverage badge" || echo "No changes to commit"
        git push
      env:
        GIT_AUTH_TOKEN: ${{ secrets.PAT_GITHUB }}
      shell: bash
      continue-on-error: true
      working-directory: ${{ github.workspace }}
